apiVersion: v2
appVersion: 2.0.0-rc2
description: A Jaeger Helm chart for Kubernetes
name: jaeger
type: application
version: 4.0.0
annotations:
  Jaegerv1Version: "1.62.0"
# CronJobs require v1.21
kubeVersion: ">= 1.21-0"
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
home: https://jaegertracing.io
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
sources:
  - https://hub.docker.com/u/jaegertracing/
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x