provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false



allInOne:
  enabled: true
  replicas: 1
  image:
    registry: ""
    repository: jaegertracing/all-in-one
    tag: ""
  service:
    headless: true
    collector:
      otlp:
        grpc:
          name: otlp-grpc
        http:
          name: otlp-http

storage:
  type: memory

agent:
  enabled: false


collector:
  enabled: false

query:
  enabled: false

