query:
  enabled: true
  service:
    type: NodePort
    nodePort: 30013

provisionDataStore:
  cassandra: true

storage:
  type: cassandra

cassandra:
  config:
    cluster_name: jaeger
    cluster_size: 1
    seed_size: 1
    dc_name: dc1
    rack_name: rack1
    endpoint_snitch: GossipingPropertyFileSnitch
    max_heap_size: 256M
    heap_new_size: 128M

schema:
  image:
    registry: ""
    repository: jaegertracing/jaeger-cassandra-schema
    tag: "2.4.0"

collector:
  enabled: true
  service:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318

ingester:
  enabled: false

agent:
  enabled: false