apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: tracing
spec:
  type: NodePort
  selector:
    app: hotrod
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
      nodePort: 30012