apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:1.74.0
          args:
            - all
            - '--verbose'
            - '--jaeger-ui=https://jaeger:8443'
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-inmemory-instance-collector.tracing:4318"