apiVersion: v2
appVersion: v2.7.1
description: Kiali is an open source project for service mesh observability, refer
  to https://www.kiali.io for details.
home: https://github.com/kiali/kiali
icon: https://raw.githubusercontent.com/kiali/kiali.io/current/assets/icons/logo.svg
keywords:
- istio
- kiali
maintainers:
- email: kiali-users@googlegroups.com
  name: Kiali
  url: https://kiali.io
name: kiali-server
sources:
- https://github.com/kiali/kiali
- https://github.com/kiali/kiali-operator
- https://github.com/kiali/helm-charts
version: 2.7.1
