Vagrant.configure("2") do |config|

  # OS 선택
  config.vm.box = "rockylinux/8"
  # Disk 확장
  config.disksize.size = "30GB"
  # 자동 업데이트 안함
  config.vbguest.auto_update = false
  # PC-VM간 마운팅 안함
  config.vm.synced_folder "./", "/vagrant", disabled: true

  config.vm.define "cicd-server" do |cicd|
    cicd.vm.hostname = "cicd-server"
    cicd.vm.network "private_network", ip: "192.168.56.20"
	cicd.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
	  vb.customize ["modifyvm", :id, "--firmware", "efi"]
	end
    cicd.vm.provision :shell, privileged: true, inline: $install_cicd
  end
end

$install_cicd = <<-SHELL

echo '======== [1] Rocky Linux 기본 설정 ========'
echo '======== [1-1] 패키지 업데이트 ========'
yum -y update

echo '======== [1-2] 타임존 설정 ========'
timedatectl set-timezone Asia/Seoul

echo '======== [1-3] Disk 확장 설정 ========'
yum install -y cloud-utils-growpart
growpart /dev/sda 4
xfs_growfs /dev/sda4

echo '======== [1-4] 방화벽 해제 ========'
systemctl stop firewalld && systemctl disable firewalld


echo '======== [2] Kubectl 설치 ========'
echo '======== [2-1] repo 설정 ========'
cat <<EOF |tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

echo '======== [2-2] Kubectl 설치 ========'
yum install -y kubectl-1.27.2-0.x86_64 --disableexcludes=kubernetes

echo '======== [2-3] Kubectl 자동완성 기능 설치 ========'
echo "source <(kubectl completion bash)" >> ~/.bashrc
echo 'alias k=kubectl' >>~/.bashrc
echo 'complete -o default -F __start_kubectl k' >>~/.bashrc


echo '======== [3] 도커 설치 ========'
# https://download.docker.com/linux/centos/8/x86_64/stable/Packages/ 저장소 경로
yum install -y yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce-3:23.0.6-1.el8 docker-ce-cli-1:23.0.6-1.el8 containerd.io-1.6.21-3.1.el8
systemctl daemon-reload
systemctl enable --now docker

echo '======== [4] OpenJDK 설치  ========'
yum install -y java-17-openjdk-1:17.0.7.0.7-3.el8

echo '======== [5] Gradle 설치  ========'
yum -y install wget unzip
wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip -P ~/
unzip -d /opt/gradle ~/gradle-*.zip
cat <<EOF |tee /etc/profile.d/gradle.sh
export GRADLE_HOME=/opt/gradle/gradle-7.6.1
export PATH=/opt/gradle/gradle-7.6.1/bin:${PATH}
EOF
chmod +x /etc/profile.d/gradle.sh
source /etc/profile.d/gradle.sh

echo '======== [6] Git 설치  ========'
yum install -y git-2.39.3-1.el8_8

echo '======== [7] Jenkins 설치  ========'
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
yum install -y java-11-openjdk-1:11.0.19.0.7-4.el8 jenkins-2.414.2-1.1
systemctl enable jenkins
systemctl start jenkins

# jeknins가 Docker를 사용할 수 있도록 설정
chmod 666 /var/run/docker.sock
usermod -aG docker jenkins

SHELL